---
# tasks file for rsync-server

- name: Rsyncd | install rsync
  become: true
  ansible.builtin.dnf:
    pkg: rsync
    state: present

- name: Rsyncd | create log directory
  become: true
  ansible.builtin.file:
    path: /var/log/rsyncd
    state: directory
    mode: 0755

- name: Rsyncd | configure shares
  become: true
  ansible.builtin.template:
    dest: /etc/rsyncd.conf
    src: etc-rsyncd.conf.j2
    mode: 0644
    # No need to reload, file is re-read on each client connection.

- name: Rsyncd | configure logrotate
  become: true
  ansible.builtin.template:
    backup: false
    dest: /etc/logrotate.d/rsyncd
    src: etc-logrotate.d-rsyncd.j2
    mode: 0644

# - name: Rsyncd | selinux allow network connect
#  become: true
#  seboolean:
#    name: rsync_export_all_ro
#    state: true
#    persistent: true
#   when: selinux_enabled

- name: Rsyncd | start and enable service
  become: true
  ansible.builtin.service:
    name: rsyncd
    enabled: true
    state: started
